name: Playground

on:
  push:
    branches:
    - master

jobs:
  first_job:
    concurrency: first
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    - name: Prints the date
      run: date

    - name: Wait
      run: sleep 1

  second_job:
    concurrency: second
    runs-on: ubuntu-latest
    needs: [first_job]
    strategy:
      matrix:
        iteration: [one, two, three]

    steps:
    - name: Prints the iteration
      run: echo ${{matrix.iteration}}

    - name: Prints the date
      run: date

  third_job:
    concurrency: third
    runs-on: ubuntu-latest
    needs: [second_job]

    steps:

    - name: Prints the date
      run: date
