name: Playground

on:
  push:
    branches:
    - master

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2

    - name: Wait
      run: sleep 10

  second_job:
    runs-on: ubuntu-latest
    needs: [first_job]

    steps:

    - name: Prints the date
      run: date
